[features]
seeds = false
skip-lint = false
[programs.localnet]
solfundme = "9kYU5QF9ecxxn7PxijJ1BCGcsos9fPJmvTF34yANWEPq"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/home/jrej/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
